buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.6'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
    maven { url 'https://maven.google.com' }
}

apply plugin: 'com.android.application'

android {
    compileSdkVersion 33
    defaultConfig {
        applicationId 'com.alburagh.alburagh.app'
        minSdkVersion 19
        targetSdkVersion 33
        versionCode 74
        versionName '7.4'
        manifestPlaceholders = [onesignal_app_id               : "c3a7bd29-26fa-4c83-ba08-977ed4879bfa",
                                // Project number pulled from dashboard, local value is ignored.
                                onesignal_google_project_number: "355349507515"]
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        lintOptions {
            abortOnError false
        }
    }
    sourceSets { main { assets.srcDirs = ['src/main/assets', 'src/main/assets/'] } }
}

repositories {
    mavenLocal()
    mavenCentral()
    google()
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.loopj.android:android-async-http:1.4.9'
    implementation 'org.jsoup:jsoup:1.13.1'

    implementation 'androidx.recyclerview:recyclerview:1.2.0'
    implementation 'com.duowan.android.netroid:netroid:1.2.1'
    implementation 'com.github.filippudak.progresspieview:library:1.0.4'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.github.ksoichiro:androidpagecontrol:0.1.1'
    implementation 'com.android.billingclient:billing:6.2.0'
    //==============================================================================================
    // OneSignal.com
    //==============================================================================================
    //    implementation 'com.onesignal:OneSignal:[3.9.1, 3.99.99]'
    //==============================================================================================
}